{% set version = "2.2.2" %}

package:
  name: libgdal
  version: {{ version }}

source:
  fn: gdal-{{ version }}.tar.gz
  url: http://download.osgeo.org/gdal/{{ version }}/gdal-{{ version }}.tar.gz
  sha256: 14c1f78a60f429ad51c08d75cbf49771f1e6b20e7385c6e8379b40e8dfa39544
  patches:
    # Fixes compilation problems with JPEG.
    # https://lists.osgeo.org/pipermail/gdal-dev/2016-January/043443.html
    - disable_jpeg12.patch
    # BUILT_AS_DYNAMIC_LIB.
    - windowshdf5.patch
    # Use multiple cores on Windows.
    - multiprocessor.patch

build:
  number: 4
  skip: True  # [win and py36]
  features:
    - vc9  # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and (py35 or py36)]

requirements:
  build:
    - python  # [win]
    - cmake  # [win]
    - curl >=7.44.0,<8
    - expat 2.1.*
    - freexl
    - geos 3.5.1
    - giflib 5.1.*  # [not win]
    - hdf4
    - hdf5 1.8.18|1.8.18.*
    - jpeg 9*
    - json-c  # [not win]
    - kealib >=1.4.7,<1.5
    - libdap4 3.18.*  # [not win]
    - libkml  1.3.0  # [not win]
    - libnetcdf 4.4.*
    - libpng >=1.6.22,<1.6.31
    - libspatialite
    - libtiff >=4.0.3,<4.0.8
    - openjpeg 2.1.0
    - poppler  # [not win]
    - postgresql
    - proj4 4.9.3
    - sqlite 3.13.*
    - xerces-c
    - zlib 1.2.8  # [not win]
    - xz 5.2.*
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and (py35 or py36)]
  run:
    - curl >=7.44.0,<8
    - expat 2.1.*
    - freexl
    - geos 3.5.1
    - giflib 5.1.*  # [not win]
    - hdf4
    - hdf5 1.8.18|1.8.18.*
    - jpeg 9*
    - json-c  # [not win]
    - kealib >=1.4.7,<1.5
    - libdap4 3.18.*  # [not win]
    - libkml  1.3.0  # [not win]
    - libnetcdf 4.4.*
    - libpng >=1.6.22,<1.6.31
    - libpq
    - libspatialite
    - libtiff >=4.0.3,<4.0.8
    - openjpeg >=2.1,<2.3
    - poppler  # [not win]
    - proj4 4.9.3
    - sqlite 3.13.*
    - xerces-c
    - zlib 1.2.8  # [not win]
    - xz 5.2.*
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and (py35 or py36)]

test:
  files:
    - test_data
  commands:
    - gdal_grid --version
    - gdal_rasterize --version
    - gdal_translate --version
    - gdaladdo --version
    - gdalenhance --version
    - gdalwarp --version
    - gdalinfo --formats
    - gdalinfo http://thredds.nersc.no/thredds/dodsC/greenpath/Model/topaz  # [not win]
    - conda inspect linkages -p $PREFIX libgdal  # [not win]
    - conda inspect objects -p $PREFIX libgdal  # [osx]

about:
  home: http://www.gdal.org/
  license: MIT
  license_file: LICENSE.TXT
  summary: 'The Geospatial Data Abstraction Library (GDAL).'

extra:
  recipe-maintainers:
    - ocefpaf
    - kmuehlbauer
    - gillins
